[workspace]
name = "cue-example"
cache_dir = ".cue/cache"
remote_cache_url = "http://localhost:3000"

[tasks.build]
command = "cargo build"
inputs = ["src/**/*.rs", "Cargo.toml", "Cargo.lock"]
outputs = ["target/"]
dependencies = []
cache = true

[tasks.test]
command = "cargo test"
inputs = ["src/**/*.rs", "tests/**/*.rs"]
outputs = []
dependencies = ["build"]
cache = true

[tasks.clean]
command = "cargo clean"
inputs = []
outputs = []
dependencies = []
cache = false

[tasks.lint]
command = "cargo clippy"
inputs = ["src/**/*.rs"]
outputs = []
dependencies = []
cache = true
