[project]
name = "project-3"
description = "A cue project"
version = "0.1.0"

[tasks.test]
command = "cargo test"
inputs = [
    "src/**/*.rs",
    "tests/**/*.rs",
]
outputs = []
dependencies = ["build"]
cache = true
description = "Run tests"

[tasks.build]
command = "cargo build"
inputs = [
    "src/**/*.rs",
    "Cargo.toml",
]
outputs = ["target/"]
dependencies = []
cache = true
description = "Build the project"

[tasks.slow]
command = "sleep 3"
inputs = []
outputs = []
dependencies = []
cache = false
description = "A slow task for testing"
