[project]
name = "example-failure"
description = "A cue project that fails"
version = "0.1.0"

[tasks.slow]
command = "sleep 10 && exit 1"
inputs = []
outputs = []
dependencies = []
cache = false
description = "A slow task that fails after 10 seconds"
